In [27]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

# Set up the Selenium WebDriver (make sure to have the appropriate webdriver installed)
driver = webdriver.Edge(executable_path=r"C:\Program Files (x86)\msedgedriver.exe")

# URL of the webpage containing the dropdown menu
url = "https://www.nba.com/stats/teams/traditional?dir=A&sort=W_PCT"
driver.get(url)

In [28]:
# Introduce a wait to allow the page to load
time.sleep(5)

years = driver.find_elements_by_class_name("DropDown_select__4pIg9")[0].text.split('\n')
table_data = []

# Season 2023-24
year = years[0]

# Find the table on the page
table = WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.XPATH, '//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table'))
)

# Store the table data in a variable for looping
tbody = table.find_element(By.TAG_NAME, 'tbody')
rows = WebDriverWait(driver, 10).until(
    EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
)

# table_data = []
for row in rows:
    try:
        row_cells = row.find_elements(By.TAG_NAME, 'td')
        # Check if the row contains cells (data) before processing
        if row_cells:
            row_text = [cell.text for cell in row_cells]
            row_text.append(year)
            table_data.append(row_text) 
            print(f"Adding data for team rank {row_text[0]} {row_text[1]} for the {year} season")
    except:
        # Handle StaleElementReferenceException by refinding the row
        rows = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
        )
        
# Get table headers
headers = table.find_element_by_xpath('//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table/thead').text.split(' ')
headers.append('YEAR')

# Close the browser window
driver.quit()

Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank 1 Boston Celtics for the 2023-24 season
Adding data for team rank 2 Minnesota Timberwolves for the 2023-24 season
Adding data for team rank 3 Milwaukee Bucks for the 2023-24 season
Adding data for team rank 3 Philadelphia 76ers for the 2023-24 season
Adding data for team rank 5 Orlando Magic for the 2023-24 season
Adding data for team rank 6 Denver Nuggets for the 2023-24 season
Adding data for team rank 7 Oklahoma City Thunder for the 2023-24 season
Adding data for team rank 8 Dallas Mavericks for the 2023-24 season
Adding data for team rank 9 Sacramento Kings for the 2023-24 season
Adding data for team rank 10 Houston Rockets for the 2023-24 season
Adding data for team rank 11 LA Clippers for the 2023-24 season
Adding data for team rank 11 New York Knicks for the 2023-24 season
Adding data for team rank 13 Los Angeles Lakers for the 2023-24 season
Adding data for team rank 13 New Orleans Pelicans for the 2023-24 season
Adding data for team rank 15 Indiana Pacers for the 2023-24 season
Adding data for team rank 16 Miami Heat for the 2023-24 season
Adding data for team rank 17 Brooklyn Nets for the 2023-24 season
Adding data for team rank 18 Cleveland Cavaliers for the 2023-24 season
Adding data for team rank 18 Phoenix Suns for the 2023-24 season
Adding data for team rank 20 Atlanta Hawks for the 2023-24 season
Adding data for team rank 20 Golden State Warriors for the 2023-24 season
Adding data for team rank 22 Toronto Raptors for the 2023-24 season
Adding data for team rank 23 Chicago Bulls for the 2023-24 season
Adding data for team rank 24 Utah Jazz for the 2023-24 season
Adding data for team rank 25 Charlotte Hornets for the 2023-24 season
Adding data for team rank 26 Portland Trail Blazers for the 2023-24 season
Adding data for team rank 27 Memphis Grizzlies for the 2023-24 season
Adding data for team rank 28 San Antonio Spurs for the 2023-24 season
Adding data for team rank 28 Washington Wizards for the 2023-24 season
Adding data for team rank 30 Detroit Pistons for the 2023-24 season

In [29]:
# Filter out table
table_data = table_data[12:]

In [30]:
# Remove empty column
headers.pop(0)

''

In [31]:
import pandas as pd

# Getting the headers from the data array
# It is important to remove them from the data array afterwards in order to be parsed correctly by Pandas
team_stats = pd.DataFrame(table_data, columns=headers)
team_stats

,,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,24,19,5,.792,48.4,117.8,42.4,88.6,...,46.1,25.0,13.8,7.0,6.1,3.7,17.7,18.6,8.8,2023-24
1,2,Minnesota Timberwolves,23,18,5,.783,48.2,113.0,41.0,85.5,...,45.9,25.6,15.0,7.2,6.3,4.8,19.4,20.7,7.3,2023-24
2,3,Milwaukee Bucks,24,17,7,.708,48.4,123.3,44.4,88.8,...,43.8,25.5,13.7,7.2,5.7,4.3,20.0,21.0,3.9,2023-24
3,3,Philadelphia 76ers,24,17,7,.708,48.2,122.4,42.9,89.6,...,45.9,26.0,13.2,9.0,6.1,5.9,20.6,20.5,10.2,2023-24
4,5,Orlando Magic,24,16,8,.667,48.0,113.9,41.4,86.5,...,43.6,25.3,15.4,8.4,5.5,5.0,21.8,23.3,4.2,2023-24
5,6,Denver Nuggets,26,17,9,.654,48.0,114.6,44.1,90.2,...,44.5,29.7,12.5,7.1,5.2,5.0,19.0,19.2,4.1,2023-24
6,7,Oklahoma City Thunder,23,15,8,.652,48.4,120.5,43.7,89.5,...,41.1,25.4,13.0,8.7,6.2,5.3,20.4,20.3,7.0,2023-24
7,8,Dallas Mavericks,24,15,9,.625,48.0,119.4,42.9,90.7,...,42.0,25.7,12.0,6.4,4.7,4.1,18.3,21.7,2.4,2023-24
8,9,Sacramento Kings,23,14,9,.609,48.4,116.8,42.0,90.3,...,43.8,27.9,13.8,7.2,3.9,4.6,20.9,20.0,-0.3,2023-24
9,10,Houston Rockets,22,13,9,.591,48.2,109.5,39.8,87.1,...,46.1,25.3,13.3,6.3,4.5,5.2,21.9,19.9,4.4,2023-24
10,11,LA Clippers,24,14,10,.583,48.2,114.4,41.8,87.7,...,44.1,25.0,13.4,8.6,5.3,4.7,20.2,20.6,4.9,2023-24
11,11,New York Knicks,24,14,10,.583,48.0,114.2,41.2,89.3,...,45.5,24.1,13.1,7.8,3.1,5.1,17.9,21.0,3.7,2023-24
12,13,Los Angeles Lakers,26,15,11,.577,48.4,114.0,42.2,86.4,...,44.6,27.0,14.4,7.7,5.6,4.5,17.3,20.9,0.5,2023-24
13,13,New Orleans Pelicans,26,15,11,.577,48.0,114.8,41.9,87.8,...,44.4,26.1,13.7,8.2,4.5,5.1,20.0,20.8,0.8,2023-24
14,15,Indiana Pacers,23,13,10,.565,48.0,128.2,48.1,95.3,...,40.4,30.5,13.1,7.8,6.3,6.0,22.7,19.2,2.2,2023-24
15,16,Miami Heat,25,14,11,.560,48.0,112.8,40.2,85.5,...,41.1,26.4,13.3,7.6,3.2,5.0,18.7,20.2,1.0,2023-24
16,17,Brooklyn Nets,24,13,11,.542,48.2,116.3,43.0,91.5,...,47.7,25.9,13.2,6.2,5.5,4.5,18.5,18.3,2.0,2023-24
17,18,Cleveland Cavaliers,25,13,12,.520,48.2,110.5,41.3,87.2,...,44.2,24.9,14.6,8.0,4.7,5.4,19.2,19.0,-0.4,2023-24
18,18,Phoenix Suns,25,13,12,.520,48.6,115.4,40.5,85.4,...,43.6,26.2,14.8,6.9,6.6,5.1,19.3,22.1,1.2,2023-24
19,20,Atlanta Hawks,24,10,14,.417,48.2,122.6,44.3,94.3,...,44.8,25.8,13.8,8.6,4.5,6.0,18.8,19.8,0.1,2023-24
20,20,Golden State Warriors,24,10,14,.417,48.4,115.5,40.6,90.0,...,47.3,27.4,15.7,7.0,3.3,4.5,22.3,20.6,-0.1,2023-24
21,22,Toronto Raptors,25,10,15,.400,48.4,112.5,42.4,90.3,...,45.0,29.0,14.2,7.7,4.7,5.2,18.7,18.7,-2.3,2023-24
22,23,Chicago Bulls,26,10,16,.385,48.8,109.7,40.5,90.6,...,42.8,23.6,11.8,8.1,4.6,4.9,20.1,19.4,-3.8,2023-24
23,24,Utah Jazz,25,9,16,.360,48.6,112.0,40.9,90.9,...,46.7,26.7,17.3,6.7,6.0,6.4,20.0,19.3,-7.8,2023-24
24,25,Charlotte Hornets,23,7,16,.304,48.2,112.7,42.5,89.3,...,42.0,25.7,14.0,7.0,4.8,4.7,20.3,18.8,-7.7,2023-24
25,26,Portland Trail Blazers,23,6,17,.261,48.7,106.8,39.1,90.5,...,41.1,22.3,15.6,8.8,4.5,6.7,20.6,19.0,-6.9,2023-24
26,27,Memphis Grizzlies,24,6,18,.250,48.2,106.0,39.1,89.9,...,42.0,23.8,14.5,7.6,6.4,6.8,21.5,19.1,-6.3,2023-24
27,28,San Antonio Spurs,24,4,20,.167,48.4,110.6,41.5,91.3,...,43.3,29.0,16.0,6.9,6.0,3.8,19.7,18.6,-10.5,2023-24
28,28,Washington Wizards,24,4,20,.167,48.0,116.8,44.0,90.5,...,39.1,28.0,14.3,7.7,5.0,5.5,19.8,19.0,-10.0,2023-24
29,30,Detroit Pistons,25,2,23,.080,48.0,108.1,40.6,88.0,...,43.9,25.7,16.9,6.1,5.4,6.2,22.8,18.0,-11.3,2023-24

# Cleaning

In [32]:
# Check data types
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           30 non-null     object
 1   TEAM    30 non-null     object
 2   GP      30 non-null     object
 3   W       30 non-null     object
 4   L       30 non-null     object
 5   WIN%    30 non-null     object
 6   MIN     30 non-null     object
 7   PTS     30 non-null     object
 8   FGM     30 non-null     object
 9   FGA     30 non-null     object
 10  FG%     30 non-null     object
 11  3PM     30 non-null     object
 12  3PA     30 non-null     object
 13  3P%     30 non-null     object
 14  FTM     30 non-null     object
 15  FTA     30 non-null     object
 16  FT%     30 non-null     object
 17  OREB    30 non-null     object
 18  DREB    30 non-null     object
 19  REB     30 non-null     object
 20  AST     30 non-null     object
 21  TOV     30 non-null     object
 22  STL     30 non-null     object
 23  BLK     30 non-null     object
 24  BLKA    30 non-null     object
 25  PF      30 non-null     object
 26  PFD     30 non-null     object
 27  +/-     30 non-null     object
 28  YEAR    30 non-null     object
dtypes: object(29)
memory usage: 6.9+ KB

In [33]:
team_stats.columns

Index(['', 'TEAM', 'GP', 'W', 'L', 'WIN%', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-', 'YEAR'],
      dtype='object')

In [34]:
# Rename empty column name to 'Rank'
team_stats = team_stats.rename(columns={"": "RANK"})
team_stats.head()

,RANK,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,24,19,5,.792,48.4,117.8,42.4,88.6,...,46.1,25.0,13.8,7.0,6.1,3.7,17.7,18.6,8.8,2023-24
1,2,Minnesota Timberwolves,23,18,5,.783,48.2,113.0,41.0,85.5,...,45.9,25.6,15.0,7.2,6.3,4.8,19.4,20.7,7.3,2023-24
2,3,Milwaukee Bucks,24,17,7,.708,48.4,123.3,44.4,88.8,...,43.8,25.5,13.7,7.2,5.7,4.3,20.0,21.0,3.9,2023-24
3,3,Philadelphia 76ers,24,17,7,.708,48.2,122.4,42.9,89.6,...,45.9,26.0,13.2,9.0,6.1,5.9,20.6,20.5,10.2,2023-24
4,5,Orlando Magic,24,16,8,.667,48.0,113.9,41.4,86.5,...,43.6,25.3,15.4,8.4,5.5,5.0,21.8,23.3,4.2,2023-24

In [35]:
# Convert following columns to floats
string_columns = ['RANK', 'GP', 'W', 'L', 'WIN%', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-']
team_stats[string_columns] = team_stats[string_columns].apply(pd.to_numeric, errors='coerce')

team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RANK    30 non-null     int64
 1   TEAM    30 non-null     object
 2   GP      30 non-null     int64
 3   W       30 non-null     int64
 4   L       30 non-null     int64
 5   WIN%    30 non-null     float64
 6   MIN     30 non-null     float64
 7   PTS     30 non-null     float64
 8   FGM     30 non-null     float64
 9   FGA     30 non-null     float64
 10  FG%     30 non-null     float64
 11  3PM     30 non-null     float64
 12  3PA     30 non-null     float64
 13  3P%     30 non-null     float64
 14  FTM     30 non-null     float64
 15  FTA     30 non-null     float64
 16  FT%     30 non-null     float64
 17  OREB    30 non-null     float64
 18  DREB    30 non-null     float64
 19  REB     30 non-null     float64
 20  AST     30 non-null     float64
 21  TOV     30 non-null     float64
 22  STL     30 non-null     float64
 23  BLK     30 non-null     float64
 24  BLKA    30 non-null     float64
 25  PF      30 non-null     float64
 26  PFD     30 non-null     float64
 27  +/-     30 non-null     float64
 28  YEAR    30 non-null     object
dtypes: float64(23), int64(4), object(2)
memory usage: 6.9+ KB

In [36]:
team_stats['TEAM'].dropna()

0             Boston Celtics
1     Minnesota Timberwolves
2            Milwaukee Bucks
3         Philadelphia 76ers
4              Orlando Magic
5             Denver Nuggets
6      Oklahoma City Thunder
7           Dallas Mavericks
8           Sacramento Kings
9            Houston Rockets
10               LA Clippers
11           New York Knicks
12        Los Angeles Lakers
13      New Orleans Pelicans
14            Indiana Pacers
15                Miami Heat
16             Brooklyn Nets
17       Cleveland Cavaliers
18              Phoenix Suns
19             Atlanta Hawks
20     Golden State Warriors
21           Toronto Raptors
22             Chicago Bulls
23                 Utah Jazz
24         Charlotte Hornets
25    Portland Trail Blazers
26         Memphis Grizzlies
27         San Antonio Spurs
28        Washington Wizards
29           Detroit Pistons
Name: TEAM, dtype: object

In [37]:
# Add short form team name
team_short_forms = {
    'Boston Celtics': 'BOS', 
    'Minnesota Timberwolves': 'MIN', 
    'Orlando Magic': 'ORL', 
    'Denver Nuggets': 'DEN', 
    'Milwaukee Bucks': 'MIL', 
    'Oklahoma City Thunder': 'OKC', 
    'New York Knicks': 'NYK',
    'Philadelphia 76ers': 'PHI',
    'Dallas Mavericks': 'DAL',
    'Sacramento Kings': 'SAC',
    'Miami Heat': 'MIA',
    'Phoenix Suns': 'PHX',
    'Los Angeles Lakers': 'LAL',
    'New Orleans Pelicans': 'NOP', 
    'Indiana Pacers': 'IND',
    'Cleveland Cavaliers': 'CLE',
    'Atlanta Hawks': 'ATL',
    'Brooklyn Nets': 'BKN', 
    'Houston Rockets': 'HOU', 
    'LA Clippers': 'LAC', 
    'Golden State Warriors': 'GSW', 
    'Toronto Raptors': 'TOR',
    'Charlotte Hornets': 'CHA',
    'Portland Trail Blazers': 'POR' ,
    'Utah Jazz': 'UTA', 
    'Chicago Bulls': 'CHI',
    'Memphis Grizzlies': 'MEM',
    'San Antonio Spurs': 'SAS',
    'Washington Wizards': 'WAS',
    'Detroit Pistons': 'DET',
    
}
team_stats['TEAM'] = team_stats['TEAM'].map(team_short_forms)

In [38]:
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RANK    30 non-null     int64
 1   TEAM    30 non-null     object
 2   GP      30 non-null     int64
 3   W       30 non-null     int64
 4   L       30 non-null     int64
 5   WIN%    30 non-null     float64
 6   MIN     30 non-null     float64
 7   PTS     30 non-null     float64
 8   FGM     30 non-null     float64
 9   FGA     30 non-null     float64
 10  FG%     30 non-null     float64
 11  3PM     30 non-null     float64
 12  3PA     30 non-null     float64
 13  3P%     30 non-null     float64
 14  FTM     30 non-null     float64
 15  FTA     30 non-null     float64
 16  FT%     30 non-null     float64
 17  OREB    30 non-null     float64
 18  DREB    30 non-null     float64
 19  REB     30 non-null     float64
 20  AST     30 non-null     float64
 21  TOV     30 non-null     float64
 22  STL     30 non-null     float64
 23  BLK     30 non-null     float64
 24  BLKA    30 non-null     float64
 25  PF      30 non-null     float64
 26  PFD     30 non-null     float64
 27  +/-     30 non-null     float64
 28  YEAR    30 non-null     object
dtypes: float64(23), int64(4), object(2)
memory usage: 6.9+ KB

In [39]:
file_path = 'team_stats.csv'
team_stats.to_csv(file_path, index=False)