In [27]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

# Set up the Selenium WebDriver (make sure to have the appropriate webdriver installed)
driver = webdriver.Edge(executable_path=r"C:\Program Files (x86)\msedgedriver.exe")

# URL of the webpage containing the dropdown menu
url = "https://www.nba.com/stats/teams/traditional?dir=A&sort=W_PCT"
driver.get(url)

In [28]:
# Introduce a wait to allow the page to load
time.sleep(5)

years = driver.find_elements_by_class_name("DropDown_select__4pIg9")[0].text.split('\n')
table_data = []

# Season 2023-24
year = years[0]

# Find the table on the page
table = WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.XPATH, '//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table'))
)

# Store the table data in a variable for looping
tbody = table.find_element(By.TAG_NAME, 'tbody')
rows = WebDriverWait(driver, 10).until(
    EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
)

# table_data = []
for row in rows:
    try:
        row_cells = row.find_elements(By.TAG_NAME, 'td')
        # Check if the row contains cells (data) before processing
        if row_cells:
            row_text = [cell.text for cell in row_cells]
            row_text.append(year)
            table_data.append(row_text) 
            print(f"Adding data for team rank {row_text[0]} {row_text[1]} for the {year} season")
    except:
        # Handle StaleElementReferenceException by refinding the row
        rows = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
        )
        
# Get table headers
headers = table.find_element_by_xpath('//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table/thead').text.split(' ')
headers.append('YEAR')

# Close the browser window
driver.quit()

Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank 1 Boston Celtics for the 2023-24 season
Adding data for team rank 1 Minnesota Timberwolves for the 2023-24 season
Adding data for team rank 3 Milwaukee Bucks for the 2023-24 season
Adding data for team rank 4 Philadelphia 76ers for the 2023-24 season
Adding data for team rank 5 Oklahoma City Thunder for the 2023-24 season
Adding data for team rank 6 Denver Nuggets for the 2023-24 season
Adding data for team rank 7 Orlando Magic for the 2023-24 season
Adding data for team rank 7 Sacramento Kings for the 2023-24 season
Adding data for team rank 9 Dallas Mavericks for the 2023-24 season
Adding data for team rank 9 LA Clippers for the 2023-24 season
Adding data for team rank 11 New Orleans Pelicans for the 2023-24 season
Adding data for team rank 12 New York Knicks for the 2023-24 season
Adding data for team rank 13 Cleveland Cavaliers for the 2023-24 season
Adding data for team rank 13 Los Angeles Lakers for the 2023-24 season
Adding data for team rank 13 Miami Heat for the 2023-24 season
Adding data for team rank 16 Houston Rockets for the 2023-24 season
Adding data for team rank 17 Phoenix Suns for the 2023-24 season
Adding data for team rank 18 Indiana Pacers for the 2023-24 season
Adding data for team rank 19 Brooklyn Nets for the 2023-24 season
Adding data for team rank 20 Golden State Warriors for the 2023-24 season
Adding data for team rank 21 Atlanta Hawks for the 2023-24 season
Adding data for team rank 21 Toronto Raptors for the 2023-24 season
Adding data for team rank 23 Chicago Bulls for the 2023-24 season
Adding data for team rank 24 Utah Jazz for the 2023-24 season
Adding data for team rank 25 Charlotte Hornets for the 2023-24 season
Adding data for team rank 26 Memphis Grizzlies for the 2023-24 season
Adding data for team rank 26 Portland Trail Blazers for the 2023-24 season
Adding data for team rank 28 San Antonio Spurs for the 2023-24 season
Adding data for team rank 29 Washington Wizards for the 2023-24 season
Adding data for team rank 30 Detroit Pistons for the 2023-24 season

In [29]:
# Filter out table
table_data = table_data[12:]

In [30]:
# Remove empty column
headers.pop(0)

''

In [31]:
import pandas as pd

# Getting the headers from the data array
# It is important to remove them from the data array afterwards in order to be parsed correctly by Pandas
team_stats = pd.DataFrame(table_data, columns=headers)
team_stats

,,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,25,20,5,.800,48.4,117.6,42.5,88.8,...,46.5,24.7,13.8,6.9,6.2,3.7,17.7,18.5,9.1,2023-24
1,1,Minnesota Timberwolves,25,20,5,.800,48.2,113.5,41.3,85.5,...,45.5,25.9,15.0,7.4,6.3,4.8,19.3,20.4,7.6,2023-24
2,3,Milwaukee Bucks,26,19,7,.731,48.4,124.4,44.7,88.8,...,44.0,25.5,13.8,7.0,5.6,4.3,20.3,21.0,5.2,2023-24
3,4,Philadelphia 76ers,26,18,8,.692,48.2,122.2,43.1,89.5,...,45.8,26.0,13.0,9.0,6.2,5.9,20.3,20.1,11.3,2023-24
4,5,Oklahoma City Thunder,25,17,8,.680,48.4,120.2,43.6,89.4,...,41.6,25.5,12.9,8.6,6.4,5.0,20.2,20.3,7.2,2023-24
5,6,Denver Nuggets,28,18,10,.643,48.0,115.3,44.2,90.2,...,44.6,29.6,12.3,7.0,5.0,5.0,19.1,19.3,4.7,2023-24
6,7,Orlando Magic,25,16,9,.640,48.0,113.2,41.1,86.6,...,43.6,25.0,15.2,8.4,5.4,5.2,21.6,23.1,3.4,2023-24
7,7,Sacramento Kings,25,16,9,.640,48.4,118.2,42.6,90.5,...,43.8,28.5,13.7,7.2,3.8,4.6,20.9,19.8,1.0,2023-24
8,9,Dallas Mavericks,26,16,10,.615,48.0,119.3,43.0,91.0,...,42.2,25.5,12.0,6.2,4.4,4.0,18.3,21.6,1.7,2023-24
9,9,LA Clippers,26,16,10,.615,48.2,117.0,42.7,88.1,...,44.1,25.4,13.1,8.4,5.4,4.7,20.2,20.7,6.3,2023-24
10,11,New Orleans Pelicans,27,16,11,.593,48.0,116.0,42.4,88.1,...,44.7,26.5,13.7,8.3,4.4,5.1,19.9,20.6,2.1,2023-24
11,12,New York Knicks,26,15,11,.577,48.0,114.5,41.3,89.4,...,45.5,23.8,13.1,7.6,3.3,5.0,18.0,20.9,2.7,2023-24
12,13,Cleveland Cavaliers,27,15,12,.556,48.4,112.0,41.8,88.1,...,44.1,25.3,14.3,7.9,4.7,5.3,19.5,19.6,0.1,2023-24
13,13,Los Angeles Lakers,27,15,12,.556,48.4,113.8,42.2,86.9,...,44.4,27.1,14.2,7.7,5.5,4.5,17.3,20.7,0.3,2023-24
14,13,Miami Heat,27,15,12,.556,48.0,112.8,40.4,85.4,...,40.7,26.4,13.2,7.7,3.1,5.1,18.7,20.1,0.8,2023-24
15,16,Houston Rockets,24,13,11,.542,48.4,110.7,40.3,87.6,...,45.5,25.7,13.2,6.5,4.5,5.1,22.3,20.3,3.4,2023-24
16,17,Phoenix Suns,26,14,12,.538,48.6,115.3,40.5,85.6,...,44.0,26.3,14.9,6.9,6.6,5.2,19.2,22.2,1.3,2023-24
17,18,Indiana Pacers,25,13,12,.520,48.0,127.4,48.0,95.1,...,40.2,30.6,13.1,7.8,6.4,6.1,22.4,19.0,0.3,2023-24
18,19,Brooklyn Nets,26,13,13,.500,48.2,116.1,43.0,91.5,...,47.0,26.1,13.3,6.1,5.7,4.6,18.6,18.3,1.0,2023-24
19,20,Golden State Warriors,26,12,14,.462,48.4,115.9,40.9,89.9,...,46.9,27.6,15.6,7.1,3.4,4.6,21.9,20.6,0.2,2023-24
20,21,Atlanta Hawks,26,11,15,.423,48.2,122.7,44.2,93.6,...,44.2,25.5,13.8,8.4,4.7,5.8,19.1,20.2,0.0,2023-24
21,21,Toronto Raptors,26,11,15,.423,48.4,112.5,42.5,90.1,...,45.3,29.0,14.3,7.6,4.7,5.3,18.6,18.7,-1.7,2023-24
22,23,Chicago Bulls,28,11,17,.393,48.7,109.9,40.4,90.0,...,42.8,23.7,11.9,8.0,4.8,4.9,19.9,19.3,-3.4,2023-24
23,24,Utah Jazz,27,10,17,.370,48.6,112.2,40.9,90.7,...,46.5,26.9,17.0,6.7,5.9,6.3,19.7,19.1,-7.3,2023-24
24,25,Charlotte Hornets,25,7,18,.280,48.2,111.0,42.0,89.4,...,41.6,25.0,14.0,6.9,4.8,4.7,20.0,18.6,-9.8,2023-24
25,26,Memphis Grizzlies,25,6,19,.240,48.2,105.6,38.7,89.7,...,42.1,23.9,14.8,7.6,6.3,7.0,21.4,19.1,-6.8,2023-24
26,26,Portland Trail Blazers,25,6,19,.240,48.6,107.6,39.5,90.4,...,41.0,22.2,15.4,8.8,4.4,6.4,20.6,19.0,-6.9,2023-24
27,28,San Antonio Spurs,25,4,21,.160,48.4,110.6,41.4,91.4,...,43.1,29.0,15.8,6.9,6.0,3.8,19.5,18.6,-11.6,2023-24
28,29,Washington Wizards,26,4,22,.154,48.0,117.0,43.8,90.5,...,39.3,27.7,14.0,7.5,5.1,5.5,20.0,19.1,-9.9,2023-24
29,30,Detroit Pistons,27,2,25,.074,48.0,108.9,41.0,88.5,...,43.3,25.6,16.4,6.3,5.2,6.4,22.9,18.4,-11.9,2023-24

In [55]:
team_stats.loc[team_stats['TEAM'] == 'Washington Wizards']

Empty DataFrame
Columns: [RANK, TEAM, GP, W, L, WIN%, MIN, PTS, FGM, FGA, FG%, 3PM, 3PA, 3P%, FTM, FTA, FT%, OREB, DREB, REB, AST, TOV, STL, BLK, BLKA, PF, PFD, +/-, YEAR]
Index: []

[0 rows x 29 columns]

# Cleaning

In [32]:
# Check data types
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           30 non-null     object
 1   TEAM    30 non-null     object
 2   GP      30 non-null     object
 3   W       30 non-null     object
 4   L       30 non-null     object
 5   WIN%    30 non-null     object
 6   MIN     30 non-null     object
 7   PTS     30 non-null     object
 8   FGM     30 non-null     object
 9   FGA     30 non-null     object
 10  FG%     30 non-null     object
 11  3PM     30 non-null     object
 12  3PA     30 non-null     object
 13  3P%     30 non-null     object
 14  FTM     30 non-null     object
 15  FTA     30 non-null     object
 16  FT%     30 non-null     object
 17  OREB    30 non-null     object
 18  DREB    30 non-null     object
 19  REB     30 non-null     object
 20  AST     30 non-null     object
 21  TOV     30 non-null     object
 22  STL     30 non-null     object
 23  BLK     30 non-null     object
 24  BLKA    30 non-null     object
 25  PF      30 non-null     object
 26  PFD     30 non-null     object
 27  +/-     30 non-null     object
 28  YEAR    30 non-null     object
dtypes: object(29)
memory usage: 6.9+ KB

In [33]:
team_stats.columns

Index(['', 'TEAM', 'GP', 'W', 'L', 'WIN%', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-', 'YEAR'],
      dtype='object')

In [34]:
# Rename empty column name to 'Rank'
team_stats = team_stats.rename(columns={"": "RANK"})
team_stats.head()

,RANK,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,25,20,5,.800,48.4,117.6,42.5,88.8,...,46.5,24.7,13.8,6.9,6.2,3.7,17.7,18.5,9.1,2023-24
1,1,Minnesota Timberwolves,25,20,5,.800,48.2,113.5,41.3,85.5,...,45.5,25.9,15.0,7.4,6.3,4.8,19.3,20.4,7.6,2023-24
2,3,Milwaukee Bucks,26,19,7,.731,48.4,124.4,44.7,88.8,...,44.0,25.5,13.8,7.0,5.6,4.3,20.3,21.0,5.2,2023-24
3,4,Philadelphia 76ers,26,18,8,.692,48.2,122.2,43.1,89.5,...,45.8,26.0,13.0,9.0,6.2,5.9,20.3,20.1,11.3,2023-24
4,5,Oklahoma City Thunder,25,17,8,.680,48.4,120.2,43.6,89.4,...,41.6,25.5,12.9,8.6,6.4,5.0,20.2,20.3,7.2,2023-24

In [35]:
# Convert following columns to floats
string_columns = ['RANK', 'GP', 'W', 'L', 'WIN%', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-']
team_stats[string_columns] = team_stats[string_columns].apply(pd.to_numeric, errors='coerce')

team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RANK    30 non-null     int64
 1   TEAM    30 non-null     object
 2   GP      30 non-null     int64
 3   W       30 non-null     int64
 4   L       30 non-null     int64
 5   WIN%    30 non-null     float64
 6   MIN     30 non-null     float64
 7   PTS     30 non-null     float64
 8   FGM     30 non-null     float64
 9   FGA     30 non-null     float64
 10  FG%     30 non-null     float64
 11  3PM     30 non-null     float64
 12  3PA     30 non-null     float64
 13  3P%     30 non-null     float64
 14  FTM     30 non-null     float64
 15  FTA     30 non-null     float64
 16  FT%     30 non-null     float64
 17  OREB    30 non-null     float64
 18  DREB    30 non-null     float64
 19  REB     30 non-null     float64
 20  AST     30 non-null     float64
 21  TOV     30 non-null     float64
 22  STL     30 non-null     float64
 23  BLK     30 non-null     float64
 24  BLKA    30 non-null     float64
 25  PF      30 non-null     float64
 26  PFD     30 non-null     float64
 27  +/-     30 non-null     float64
 28  YEAR    30 non-null     object
dtypes: float64(23), int64(4), object(2)
memory usage: 6.9+ KB

In [36]:
team_stats['TEAM'].dropna()

0             Boston Celtics
1     Minnesota Timberwolves
2            Milwaukee Bucks
3         Philadelphia 76ers
4      Oklahoma City Thunder
5             Denver Nuggets
6              Orlando Magic
7           Sacramento Kings
8           Dallas Mavericks
9                LA Clippers
10      New Orleans Pelicans
11           New York Knicks
12       Cleveland Cavaliers
13        Los Angeles Lakers
14                Miami Heat
15           Houston Rockets
16              Phoenix Suns
17            Indiana Pacers
18             Brooklyn Nets
19     Golden State Warriors
20             Atlanta Hawks
21           Toronto Raptors
22             Chicago Bulls
23                 Utah Jazz
24         Charlotte Hornets
25         Memphis Grizzlies
26    Portland Trail Blazers
27         San Antonio Spurs
28        Washington Wizards
29           Detroit Pistons
Name: TEAM, dtype: object

In [37]:
# Add short form team name
team_short_forms = {
    'Boston Celtics': 'BOS', 
    'Minnesota Timberwolves': 'MIN', 
    'Orlando Magic': 'ORL', 
    'Denver Nuggets': 'DEN', 
    'Milwaukee Bucks': 'MIL', 
    'Oklahoma City Thunder': 'OKC', 
    'New York Knicks': 'NYK',
    'Philadelphia 76ers': 'PHI',
    'Dallas Mavericks': 'DAL',
    'Sacramento Kings': 'SAC',
    'Miami Heat': 'MIA',
    'Phoenix Suns': 'PHX',
    'Los Angeles Lakers': 'LAL',
    'New Orleans Pelicans': 'NOP', 
    'Indiana Pacers': 'IND',
    'Cleveland Cavaliers': 'CLE',
    'Atlanta Hawks': 'ATL',
    'Brooklyn Nets': 'BKN', 
    'Houston Rockets': 'HOU', 
    'LA Clippers': 'LAC', 
    'Golden State Warriors': 'GSW', 
    'Toronto Raptors': 'TOR',
    'Charlotte Hornets': 'CHA',
    'Portland Trail Blazers': 'POR' ,
    'Utah Jazz': 'UTA', 
    'Chicago Bulls': 'CHI',
    'Memphis Grizzlies': 'MEM',
    'San Antonio Spurs': 'SAS',
    'Washington Wizards': 'WAS',
    'Detroit Pistons': 'DET',
    
}
team_stats['TEAM'] = team_stats['TEAM'].map(team_short_forms)

In [38]:
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RANK    30 non-null     int64
 1   TEAM    30 non-null     object
 2   GP      30 non-null     int64
 3   W       30 non-null     int64
 4   L       30 non-null     int64
 5   WIN%    30 non-null     float64
 6   MIN     30 non-null     float64
 7   PTS     30 non-null     float64
 8   FGM     30 non-null     float64
 9   FGA     30 non-null     float64
 10  FG%     30 non-null     float64
 11  3PM     30 non-null     float64
 12  3PA     30 non-null     float64
 13  3P%     30 non-null     float64
 14  FTM     30 non-null     float64
 15  FTA     30 non-null     float64
 16  FT%     30 non-null     float64
 17  OREB    30 non-null     float64
 18  DREB    30 non-null     float64
 19  REB     30 non-null     float64
 20  AST     30 non-null     float64
 21  TOV     30 non-null     float64
 22  STL     30 non-null     float64
 23  BLK     30 non-null     float64
 24  BLKA    30 non-null     float64
 25  PF      30 non-null     float64
 26  PFD     30 non-null     float64
 27  +/-     30 non-null     float64
 28  YEAR    30 non-null     object
dtypes: float64(23), int64(4), object(2)
memory usage: 6.9+ KB

In [39]:
file_path = 'team_stats.csv'
team_stats.to_csv(file_path, index=False)