In [1]:
from selenium import webdriver
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By

# Set up the Selenium WebDriver (make sure to have the appropriate webdriver installed)
driver = webdriver.Edge(executable_path=r"C:\Program Files (x86)\msedgedriver.exe")

# URL of the webpage containing the dropdown menu
url = "https://www.nba.com/stats/teams/traditional?dir=A&sort=W_PCT"
driver.get(url)

In [2]:
# Introduce a wait to allow the page to load
time.sleep(5)

years = driver.find_elements_by_class_name("DropDown_select__4pIg9")[0].text.split('\n')

# Season 2023-24
season_23_24 = years[0]

# Find the table on the page
table = WebDriverWait(driver, 10).until(
EC.presence_of_element_located((By.XPATH, '//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table'))
)

# Store the table data in a variable for looping
tbody = table.find_element(By.TAG_NAME, 'tbody')
rows = WebDriverWait(driver, 10).until(
    EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
)

table_data = []
for row in rows:
    try:
        row_cells = row.find_elements(By.TAG_NAME, 'td')
        # Check if the row contains cells (data) before processing
        if row_cells:
            row_text = [cell.text for cell in row_cells]
            row_text.append(season_23_24)
            table_data.append(row_text) 
            print(f"Adding data for team rank {row_text[0]} {row_text[1]} for the {season_23_24} season")
    except:
        # Handle StaleElementReferenceException by refinding the row
        rows = WebDriverWait(driver, 10).until(
            EC.presence_of_all_elements_located((By.TAG_NAME, 'tr'))
        )
        
# Get table headers
headers = table.find_element_by_xpath('//*[@id="__next"]/div[2]/div[2]/div[3]/section[2]/div/div[2]/div[3]/table/thead').text.split(' ')
headers.append('YEAR')

# Close the browser window
# driver.quit()

Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank   for the 2023-24 season
Adding data for team rank 1 Boston Celtics for the 2023-24 season
Adding data for team rank 2 Minnesota Timberwolves for the 2023-24 season
Adding data for team rank 3 Orlando Magic for the 2023-24 season
Adding data for team rank 4 Denver Nuggets for the 2023-24 season
Adding data for team rank 4 Milwaukee Bucks for the 2023-24 season
Adding data for team rank 6 Oklahoma City Thunder for the 2023-24 season
Adding data for team rank 7 New York Knicks for the 2023-24 season
Adding data for team rank 7 Philadelphia 76ers for the 2023-24 season
Adding data for team rank 9 Dallas Mavericks for the 2023-24 season
Adding data for team rank 9 Phoenix Suns for the 2023-24 season
Adding data for team rank 11 Sacramento Kings for the 2023-24 season
Adding data for team rank 12 Miami Heat for the 2023-24 season
Adding data for team rank 13 Los Angeles Lakers for the 2023-24 season
Adding data for team rank 13 New Orleans Pelicans for the 2023-24 season
Adding data for team rank 15 Indiana Pacers for the 2023-24 season
Adding data for team rank 16 Cleveland Cavaliers for the 2023-24 season
Adding data for team rank 17 Atlanta Hawks for the 2023-24 season
Adding data for team rank 17 Brooklyn Nets for the 2023-24 season
Adding data for team rank 17 Houston Rockets for the 2023-24 season
Adding data for team rank 20 Golden State Warriors for the 2023-24 season
Adding data for team rank 21 Toronto Raptors for the 2023-24 season
Adding data for team rank 22 LA Clippers for the 2023-24 season
Adding data for team rank 23 Charlotte Hornets for the 2023-24 season
Adding data for team rank 24 Portland Trail Blazers for the 2023-24 season
Adding data for team rank 25 Utah Jazz for the 2023-24 season
Adding data for team rank 26 Chicago Bulls for the 2023-24 season
Adding data for team rank 27 Memphis Grizzlies for the 2023-24 season
Adding data for team rank 28 San Antonio Spurs for the 2023-24 season
Adding data for team rank 28 Washington Wizards for the 2023-24 season
Adding data for team rank 30 Detroit Pistons for the 2023-24 season

In [3]:
print(table_data)

[['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['', '', '', '', '', '', '', '2023-24'], ['1', 'Boston Celtics', '19', '15', '4', '.789', '48.5', '116.7', '41.8', '88.3', '47.3', '15.6', '42.8', '36.5', '17.5', '22.1', '79.3', '10.3', '36.7', '47.1', '24.8', '13.9', '6.6', '5.7', '3.9', '17.7', '18.6', '9.4', '2023-24'], ['2', 'Minnesota Timberwolves', '18', '14', '4', '.778', '48.3', '112.3', '40.9', '84.9', '48.2', '11.5', '31.0', '37.1', '19.0', '24.3', '78.1', '9.4', '35.8', '45.2', '25.3', '15.3', '7.7', '6.5', '4.9', '19.5', '20.9', '7.0', '2023-24'], ['3', 'Orlando Magic', '19', '14', '5', '.737', '48.0', '114.9', '41.4', '86.5', '47.9', '10.7', '30.0', '35.6', '21.4', '27.9', '76.8', '11.5', '32.7', '44.2', '25.7', '15.9', '9.1', '5.6', '5.2', '21.6', '23.6', '6.0', '2023-24'], ['4', 'Denver Nuggets', '19', '13', '6', '.684', '48.0', '114.2', '43.9', '89.5', '49.1', '11.8', '32.1', '36.8', '14.5', '20.4', '71.1', '11.5', '32.9', '44.4', '29.4', '13.1', '6.9', '5.1', '4.7', '19.1', '19.4', '4.4', '2023-24'], ['4', 'Milwaukee Bucks', '19', '13', '6', '.684', '48.3', '120.5', '43.3', '88.5', '49.0', '14.1', '37.9', '37.1', '19.8', '25.8', '76.9', '9.2', '34.6', '43.8', '24.6', '13.7', '7.4', '5.4', '4.1', '19.8', '20.6', '2.6', '2023-24'], ['6', 'Oklahoma City Thunder', '18', '12', '6', '.667', '48.3', '119.4', '43.3', '87.6', '49.5', '12.9', '32.4', '39.8', '19.8', '23.2', '85.4', '7.9', '33.4', '41.3', '25.7', '13.4', '8.0', '5.9', '5.0', '20.0', '19.9', '8.5', '2023-24'], ['7', 'New York Knicks', '19', '12', '7', '.632', '48.0', '110.9', '40.0', '89.8', '44.5', '13.7', '36.3', '37.7', '17.2', '23.4', '73.6', '13.5', '33.1', '46.6', '23.1', '12.9', '7.9', '2.9', '5.5', '17.4', '20.9', '5.4', '2023-24'], ['7', 'Philadelphia 76ers', '19', '12', '7', '.632', '48.3', '120.1', '42.3', '89.0', '47.5', '12.2', '32.2', '37.7', '23.4', '27.5', '85.1', '12.3', '32.8', '45.1', '25.4', '13.6', '8.7', '6.2', '6.3', '20.9', '20.1', '7.0', '2023-24'], ['9', 'Dallas Mavericks', '18', '11', '7', '.611', '48.0', '118.1', '42.3', '91.1', '46.5', '15.7', '42.4', '37.0', '17.7', '23.8', '74.4', '10.2', '32.0', '42.2', '25.1', '11.5', '6.0', '4.1', '4.2', '18.2', '21.9', '0.6', '2023-24'], ['9', 'Phoenix Suns', '18', '11', '7', '.611', '48.8', '116.4', '40.8', '86.2', '47.4', '12.7', '32.8', '38.7', '22.1', '26.3', '83.9', '11.1', '33.1', '44.2', '26.3', '15.0', '6.9', '7.1', '5.8', '19.2', '21.9', '3.3', '2023-24'], ['11', 'Sacramento Kings', '17', '10', '7', '.588', '48.6', '116.1', '41.6', '89.8', '46.4', '14.7', '42.1', '34.9', '18.1', '24.6', '73.7', '10.9', '32.9', '43.8', '26.9', '13.8', '7.4', '4.3', '4.2', '21.3', '20.6', '-0.6', '2023-24'], ['12', 'Miami Heat', '19', '11', '8', '.579', '48.0', '112.3', '40.3', '85.8', '46.9', '12.5', '32.6', '38.2', '19.3', '22.8', '84.3', '9.5', '31.8', '41.4', '25.9', '13.2', '8.4', '3.3', '5.2', '18.4', '20.1', '1.9', '2023-24'], ['13', 'Los Angeles Lakers', '20', '11', '9', '.550', '48.5', '112.8', '41.6', '84.9', '48.9', '10.0', '29.6', '33.8', '19.7', '25.6', '77.1', '8.2', '35.8', '43.9', '26.4', '15.0', '7.4', '6.0', '4.1', '17.4', '21.3', '-1.5', '2023-24'], ['13', 'New Orleans Pelicans', '20', '11', '9', '.550', '48.0', '113.8', '42.0', '88.0', '47.7', '11.0', '31.0', '35.4', '19.0', '25.2', '75.3', '10.9', '33.6', '44.5', '26.3', '13.9', '8.2', '4.4', '5.3', '20.3', '20.9', '1.2', '2023-24'], ['15', 'Indiana Pacers', '17', '9', '8', '.529', '48.0', '127.9', '47.8', '94.8', '50.4', '14.9', '39.5', '37.8', '17.4', '22.1', '78.7', '9.8', '30.1', '39.8', '30.1', '13.2', '8.1', '6.3', '5.9', '22.7', '19.0', '2.1', '2023-24'], ['16', 'Cleveland Cavaliers', '19', '10', '9', '.526', '48.3', '110.8', '41.5', '87.3', '47.6', '11.0', '32.0', '34.4', '16.8', '21.2', '79.2', '10.6', '33.8', '44.4', '25.5', '14.7', '7.7', '5.5', '5.0', '18.8', '19.0', '-0.8', '2023-24'], ['17', 'Atlanta Hawks', '18', '9', '9', '.500', '48.3', '123.3', '43.9', '92.6', '47.4', '13.8', '37.3', '37.1', '21.7', '26.1', '83.0', '12.9', '31.5', '44.4', '25.5', '14.5', '9.2', '4.5', '5.6', '18.5', '20.4', '1.0', '2023-24'], ['17', 'Brooklyn Nets', '18', '9', '9', '.500', '48.3', '116.0', '42.9', '90.9', '47.2', '15.3', '39.4', '38.9', '14.9', '19.2', '77.5', '12.1', '35.6', '47.7', '25.8', '13.7', '6.2', '5.4', '4.3', '18.6', '17.3', '1.3', '2023-24'], ['17', 'Houston Rockets', '16', '8', '8', '.500', '48.3', '110.9', '41.3', '87.2', '47.4', '12.4', '34.6', '35.9', '15.8', '20.8', '76.0', '9.3', '34.0', '43.3', '26.4', '12.4', '6.3', '4.2', '4.7', '22.3', '19.3', '3.6', '2023-24'], ['20', 'Golden State Warriors', '19', '9', '10', '.474', '48.3', '114.9', '40.5', '89.4', '45.3', '14.6', '39.6', '36.8', '19.3', '24.6', '78.4', '12.9', '33.8', '46.7', '27.9', '15.2', '7.3', '3.5', '4.0', '22.2', '20.0', '0.4', '2023-24'], ['21', 'Toronto Raptors', '20', '9', '11', '.450', '48.5', '111.2', '42.0', '90.9', '46.2', '11.2', '33.1', '33.7', '16.1', '22.1', '72.8', '12.9', '33.2', '46.1', '28.1', '14.4', '8.0', '4.6', '5.4', '18.5', '18.8', '-1.3', '2023-24'], ['22', 'LA Clippers', '18', '8', '10', '.444', '48.3', '112.9', '41.2', '88.1', '46.8', '11.7', '32.1', '36.5', '18.8', '24.4', '77.0', '11.2', '33.4', '44.7', '24.6', '13.6', '9.3', '4.6', '4.7', '20.8', '21.1', '3.4', '2023-24'], ['23', 'Charlotte Hornets', '17', '6', '11', '.353', '48.3', '113.6', '42.8', '90.7', '47.2', '11.4', '31.0', '36.6', '16.6', '21.5', '77.3', '12.2', '32.4', '44.5', '25.4', '14.2', '7.0', '4.8', '5.0', '20.2', '19.3', '-8.5', '2023-24'], ['24', 'Portland Trail Blazers', '18', '6', '12', '.333', '48.6', '104.7', '38.8', '88.6', '43.8', '11.0', '32.5', '33.8', '16.2', '20.5', '78.9', '11.9', '28.7', '40.7', '22.2', '16.7', '8.9', '4.8', '6.6', '20.4', '18.9', '-6.8', '2023-24'], ['25', 'Utah Jazz', '19', '6', '13', '.316', '48.5', '111.7', '40.4', '90.8', '44.5', '13.8', '38.6', '35.9', '17.2', '21.3', '80.7', '14.4', '32.4', '46.8', '26.6', '17.7', '6.5', '5.4', '6.7', '20.0', '20.0', '-7.0', '2023-24'], ['26', 'Chicago Bulls', '20', '6', '14', '.300', '48.8', '106.9', '39.6', '89.1', '44.4', '11.6', '33.2', '34.9', '16.1', '20.3', '79.1', '10.9', '30.4', '41.3', '22.5', '12.3', '8.6', '4.5', '5.0', '19.8', '19.1', '-6.0', '2023-24'], ['27', 'Memphis Grizzlies', '18', '5', '13', '.278', '48.3', '105.7', '39.0', '90.7', '43.0', '12.9', '39.6', '32.7', '14.8', '19.2', '77.1', '10.9', '31.8', '42.7', '24.3', '14.4', '7.6', '6.5', '6.8', '21.2', '18.9', '-5.9', '2023-24'], ['28', 'San Antonio Spurs', '19', '3', '16', '.158', '48.5', '111.5', '41.8', '91.1', '46.0', '12.9', '36.8', '35.0', '14.9', '18.9', '79.1', '10.1', '32.2', '42.3', '29.2', '16.6', '7.0', '6.0', '3.6', '20.4', '19.1', '-12.4', '2023-24'], ['28', 'Washington Wizards', '19', '3', '16', '.158', '48.0', '116.8', '44.0', '91.1', '48.3', '12.1', '34.0', '35.4', '16.7', '21.3', '78.5', '8.4', '30.6', '39.1', '27.8', '13.7', '8.1', '4.8', '5.5', '20.0', '18.7', '-8.3', '2023-24'], ['30', 'Detroit Pistons', '19', '2', '17', '.105', '48.0', '109.6', '41.2', '89.2', '46.2', '10.5', '29.7', '35.2', '16.7', '20.7', '80.7', '12.5', '32.8', '45.3', '26.5', '17.2', '5.9', '5.7', '6.5', '23.7', '17.8', '-8.9', '2023-24']]

In [4]:
# Filter out table
table_data = table_data[12:]

In [5]:
# Remove empty column
headers.pop(0)

''

In [10]:
import pandas as pd

# Getting the headers from the data array
# It is important to remove them from the data array afterwards in order to be parsed correctly by Pandas
team_stats = pd.DataFrame(table_data, columns=headers)
team_stats.head()

,,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,19,15,4,.789,48.5,116.7,41.8,88.3,...,47.1,24.8,13.9,6.6,5.7,3.9,17.7,18.6,9.4,2023-24
1,2,Minnesota Timberwolves,18,14,4,.778,48.3,112.3,40.9,84.9,...,45.2,25.3,15.3,7.7,6.5,4.9,19.5,20.9,7.0,2023-24
2,3,Orlando Magic,19,14,5,.737,48.0,114.9,41.4,86.5,...,44.2,25.7,15.9,9.1,5.6,5.2,21.6,23.6,6.0,2023-24
3,4,Denver Nuggets,19,13,6,.684,48.0,114.2,43.9,89.5,...,44.4,29.4,13.1,6.9,5.1,4.7,19.1,19.4,4.4,2023-24
4,4,Milwaukee Bucks,19,13,6,.684,48.3,120.5,43.3,88.5,...,43.8,24.6,13.7,7.4,5.4,4.1,19.8,20.6,2.6,2023-24

# Cleaning

In [11]:
# Check data types
team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0           30 non-null     object
 1   TEAM    30 non-null     object
 2   GP      30 non-null     object
 3   W       30 non-null     object
 4   L       30 non-null     object
 5   WIN%    30 non-null     object
 6   MIN     30 non-null     object
 7   PTS     30 non-null     object
 8   FGM     30 non-null     object
 9   FGA     30 non-null     object
 10  FG%     30 non-null     object
 11  3PM     30 non-null     object
 12  3PA     30 non-null     object
 13  3P%     30 non-null     object
 14  FTM     30 non-null     object
 15  FTA     30 non-null     object
 16  FT%     30 non-null     object
 17  OREB    30 non-null     object
 18  DREB    30 non-null     object
 19  REB     30 non-null     object
 20  AST     30 non-null     object
 21  TOV     30 non-null     object
 22  STL     30 non-null     object
 23  BLK     30 non-null     object
 24  BLKA    30 non-null     object
 25  PF      30 non-null     object
 26  PFD     30 non-null     object
 27  +/-     30 non-null     object
 28  YEAR    30 non-null     object
dtypes: object(29)
memory usage: 6.9+ KB

In [25]:
# Rename empty column name to 'Rank'
team_stats.rename(columns={"": "RANK"}, inplace=False)
team_stats.head()

,RANK,TEAM,GP,W,L,WIN%,MIN,PTS,FGM,FGA,...,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,+/-,YEAR
0,1,Boston Celtics,19,15,4,.789,48.5,116.7,41.8,88.3,...,47.1,24.8,13.9,6.6,5.7,3.9,17.7,18.6,9.4,2023-24
1,2,Minnesota Timberwolves,18,14,4,.778,48.3,112.3,40.9,84.9,...,45.2,25.3,15.3,7.7,6.5,4.9,19.5,20.9,7.0,2023-24
2,3,Orlando Magic,19,14,5,.737,48.0,114.9,41.4,86.5,...,44.2,25.7,15.9,9.1,5.6,5.2,21.6,23.6,6.0,2023-24
3,4,Denver Nuggets,19,13,6,.684,48.0,114.2,43.9,89.5,...,44.4,29.4,13.1,6.9,5.1,4.7,19.1,19.4,4.4,2023-24
4,4,Milwaukee Bucks,19,13,6,.684,48.3,120.5,43.3,88.5,...,43.8,24.6,13.7,7.4,5.4,4.1,19.8,20.6,2.6,2023-24

In [28]:
# Convert following columns to floats
string_columns = ['RANK', 'TEAM', 'GP', 'W', 'L', 'WIN%', 'MIN', 'PTS', 'FGM', 'FGA', 'FG%',
       '3PM', '3PA', '3P%', 'FTM', 'FTA', 'FT%', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', '+/-']
team_stats[string_columns] = team_stats[string_columns].apply(pd.to_numeric, errors='coerce')

team_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RANK    30 non-null     int64
 1   TEAM    0 non-null      float64
 2   GP      30 non-null     int64
 3   W       30 non-null     int64
 4   L       30 non-null     int64
 5   WIN%    30 non-null     float64
 6   MIN     30 non-null     float64
 7   PTS     30 non-null     float64
 8   FGM     30 non-null     float64
 9   FGA     30 non-null     float64
 10  FG%     30 non-null     float64
 11  3PM     30 non-null     float64
 12  3PA     30 non-null     float64
 13  3P%     30 non-null     float64
 14  FTM     30 non-null     float64
 15  FTA     30 non-null     float64
 16  FT%     30 non-null     float64
 17  OREB    30 non-null     float64
 18  DREB    30 non-null     float64
 19  REB     30 non-null     float64
 20  AST     30 non-null     float64
 21  TOV     30 non-null     float64
 22  STL     30 non-null     float64
 23  BLK     30 non-null     float64
 24  BLKA    30 non-null     float64
 25  PF      30 non-null     float64
 26  PFD     30 non-null     float64
 27  +/-     30 non-null     float64
 28  YEAR    30 non-null     object
dtypes: float64(24), int64(4), object(1)
memory usage: 6.9+ KB

In [8]:
file_path = 'team_stats.csv'
team_stats.to_csv(file_path, index=False)